
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/**
 
 Tilley:  This program simply takes the list of all possible matchings generated by "match graph" and
		  selects a single matching, specified in a command line argument.  This is exported in a format
		  that complies with the "finalize_matching" format.
 
 **/


int main(int argc, char *argv[])
{

	FILE *infd = NULL;
	FILE *outfd = NULL;
	char * outfile = "matching_code/selected_matching.txt";
	char* infile = "matching_code/possible_matches.txt";
                
	infd = fopen(infile, "r");
      if (infd == NULL) {
        printf("cannot read %s\n", infile);
        exit(1);
      }
	
	outfd = fopen(outfile, "w+");
	if (outfd == NULL) {
        printf("cannot write %s\n", outfile);
        exit(1);
	}
	
	
	char matchNum[10];
	char projID[25];
	char prof[25];
	char stu[25];
	while(!feof(infd)){
		fscanf(infd, ".%s\n", matchNum);
		fscanf(infd, "%s %s %s\n",projID, prof, stu);
		while(projID[0] != '-'){
			if(atoi(matchNum) == atoi(argv[1])) fprintf(outfd, "Project: %s Faculty: %s Student: %s\n", projID, prof, stu);
			fscanf(infd, "%s %s %s\n", projID, prof, stu);
		}
	}
	
	fclose(infd);
	fclose(outfd);
	return 0;
}
